# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
