# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-06 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210706_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content',
            field=models.TextField(),
        ),
    ]
